import numpy as np
import itertools as it 

"""This file contains the Substrate class, which is used to define the structure of the neural network that will be generated by the CPPN. 
The substrate is defined by its shape, an array of the form [[x1, x2, x3, l1], [y1, y2, y3, l2], [z1, z2, z3, l3]] where x1 is the number of neurons in the first dimension of the first layer, x2 in the second dimension and so on. the number of list is the number of layer. 
the last element of each list also indicates the layer of the neural network. 
For Hyperneat to work, we need to obtain the coordinates of each neurons in the substrate, each neurons must have its coordinates between -1 and 1 so that the cppn can process them."""

def dimension_into_coordinate_layer(array_of_shape: np.ndarray) -> np.ndarray :
    """Takes an array ie [2, 3, 4, 1] is for dim x, 2 is the number of coordinates in the first dimension, 3 in the second, 4 in the third and 1 in the last.
    The last one is the layer of the neural network, we return every possible coordinate for the neurons on the current layer ie 1 here. """
    interval_array = []
    last_dimension_coordinate = [array_of_shape[-1]]
    for x in array_of_shape[:-1] :
        interval_one_dimension = np.linspace(-1.0, 1.0, x) if (x > 1) else [0.0]
        interval_array.append(interval_one_dimension)
    return np.array(list(it.product(*interval_array, last_dimension_coordinate)))

class Substrate :

    def __init__(self, shape: np.ndarray) :
        """We keep in memory the dimensions of the substrate and the coordinates of the input, 
        output and hidden layers. hidden layers are stored in a list of arrays because many hidden layers are possible.
        shape is for example [[3, 3, 3, 1], [2, 2, 2, 2], [1, 1, 1, 3]] for a substrate with 3 layers."""
        self.dimensions = len(shape[0])
        self.input_coordinates = dimension_into_coordinate_layer(shape[0])
        self.output_coordinates = dimension_into_coordinate_layer(shape[-1])
        self.hidden_coordinates = [dimension_into_coordinate_layer(layer) for layer in shape[1:-1]]